// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("retroactive_sampling")
	ScopeName = "pitr.ca/retroactivesampling/processor/retroactivesampling"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
