// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: coordinator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessorMessage_Notify
	Payload       isProcessorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorMessage) Reset() {
	*x = ProcessorMessage{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorMessage) ProtoMessage() {}

func (x *ProcessorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorMessage.ProtoReflect.Descriptor instead.
func (*ProcessorMessage) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessorMessage) GetPayload() isProcessorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessorMessage) GetNotify() *NotifyInteresting {
	if x != nil {
		if x, ok := x.Payload.(*ProcessorMessage_Notify); ok {
			return x.Notify
		}
	}
	return nil
}

type isProcessorMessage_Payload interface {
	isProcessorMessage_Payload()
}

type ProcessorMessage_Notify struct {
	Notify *NotifyInteresting `protobuf:"bytes,1,opt,name=notify,proto3,oneof"`
}

func (*ProcessorMessage_Notify) isProcessorMessage_Payload() {}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorMessage_Decision
	//	*CoordinatorMessage_Batch
	Payload       isCoordinatorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorMessage) GetPayload() isCoordinatorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorMessage) GetDecision() *TraceDecision {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetBatch() *BatchTraceDecision {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorMessage_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isCoordinatorMessage_Payload interface {
	isCoordinatorMessage_Payload()
}

type CoordinatorMessage_Decision struct {
	Decision *TraceDecision `protobuf:"bytes,1,opt,name=decision,proto3,oneof"`
}

type CoordinatorMessage_Batch struct {
	Batch *BatchTraceDecision `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*CoordinatorMessage_Decision) isCoordinatorMessage_Payload() {}

func (*CoordinatorMessage_Batch) isCoordinatorMessage_Payload() {}

type NotifyInteresting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyInteresting) Reset() {
	*x = NotifyInteresting{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyInteresting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInteresting) ProtoMessage() {}

func (x *NotifyInteresting) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInteresting.ProtoReflect.Descriptor instead.
func (*NotifyInteresting) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyInteresting) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

type TraceDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceDecision) Reset() {
	*x = TraceDecision{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceDecision) ProtoMessage() {}

func (x *TraceDecision) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceDecision.ProtoReflect.Descriptor instead.
func (*TraceDecision) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *TraceDecision) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

type BatchTraceDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceIds      [][]byte               `protobuf:"bytes,1,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTraceDecision) Reset() {
	*x = BatchTraceDecision{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTraceDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTraceDecision) ProtoMessage() {}

func (x *BatchTraceDecision) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTraceDecision.ProtoReflect.Descriptor instead.
func (*BatchTraceDecision) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *BatchTraceDecision) GetTraceIds() [][]byte {
	if x != nil {
		return x.TraceIds
	}
	return nil
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\"W\n" +
	"\x10ProcessorMessage\x128\n" +
	"\x06notify\x18\x01 \x01(\v2\x1e.coordinator.NotifyInterestingH\x00R\x06notifyB\t\n" +
	"\apayload\"\x92\x01\n" +
	"\x12CoordinatorMessage\x128\n" +
	"\bdecision\x18\x01 \x01(\v2\x1a.coordinator.TraceDecisionH\x00R\bdecision\x127\n" +
	"\x05batch\x18\x02 \x01(\v2\x1f.coordinator.BatchTraceDecisionH\x00R\x05batchB\t\n" +
	"\apayload\".\n" +
	"\x11NotifyInteresting\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\"*\n" +
	"\rTraceDecision\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\"1\n" +
	"\x12BatchTraceDecision\x12\x1b\n" +
	"\ttrace_ids\x18\x01 \x03(\fR\btraceIds2\\\n" +
	"\vCoordinator\x12M\n" +
	"\aConnect\x12\x1d.coordinator.ProcessorMessage\x1a\x1f.coordinator.CoordinatorMessage(\x010\x01B#Z!pitr.ca/retroactivesampling/protob\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_coordinator_proto_goTypes = []any{
	(*ProcessorMessage)(nil),   // 0: coordinator.ProcessorMessage
	(*CoordinatorMessage)(nil), // 1: coordinator.CoordinatorMessage
	(*NotifyInteresting)(nil),  // 2: coordinator.NotifyInteresting
	(*TraceDecision)(nil),      // 3: coordinator.TraceDecision
	(*BatchTraceDecision)(nil), // 4: coordinator.BatchTraceDecision
}
var file_coordinator_proto_depIdxs = []int32{
	2, // 0: coordinator.ProcessorMessage.notify:type_name -> coordinator.NotifyInteresting
	3, // 1: coordinator.CoordinatorMessage.decision:type_name -> coordinator.TraceDecision
	4, // 2: coordinator.CoordinatorMessage.batch:type_name -> coordinator.BatchTraceDecision
	0, // 3: coordinator.Coordinator.Connect:input_type -> coordinator.ProcessorMessage
	1, // 4: coordinator.Coordinator.Connect:output_type -> coordinator.CoordinatorMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	file_coordinator_proto_msgTypes[0].OneofWrappers = []any{
		(*ProcessorMessage_Notify)(nil),
	}
	file_coordinator_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorMessage_Decision)(nil),
		(*CoordinatorMessage_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
